### PR TITLE
Add more pages!

### PR DESCRIPTION
**Pull request by davy**
Since the list of villains was getting quite long, it seemed reasonable that there should be a /villains page to store the full list of villains, which would allow for fewer villains on the front page.

Additionally, since the header states that Ruby Villains are about "amazing bugs, atrocious hacks, and astounding disasters", I figured we should actually have some content that fulfills this need. My idea was to add an 'Evil Lairs' section -- in this case a Lair is a repo storing particularly Evil code. I added two repos to start with, but this would be something else that would be nice to crowdsource.

Additionally:
- Split content up into partials
- Moved data storage into YML files
- Added some simple Villain and Lair classes to wrap content

Next up could be to create pages for each Villain / Lair, now that there are appropriate ids and stuff (ie. villains/dr-tenderlove)

### CODE REVIEW

**Comment by davy** [comment]
ping @kerrizor -- would love your opinion.

**Comment by kerrizor** [comment]
eep! Sorry, was out of town for a bit, will take a look today :) <3

**Comment by kerrizor** [comment]
Looks good to me. We should talk at some point about how to open up a "suggest a villain/lair" section.

**Comment by davy** [comment]
@kerrizor Yes! A way for people to add their own villains / lairs is basically exactly what I want to work on next

**Pull request merged**
