### PR TITLE
Redesign + Add Villains

### PR DESCRIPTION
**Pull request by davy**
I found a neato free theme on HTML5 UP and spent some time getting it integrated! Added a nice Ruby Red theme color, and found a Golden Gate Bridge photo for the header. (I'd be interested in seeing if we could find a more villainous header photo).

I also added a few villains to the list, to get things started. I'm trying to think of a few more to add as well. =P

### CODE REVIEW

**Comment by kerrizor** [comment]
ohmuhgoshiloveit! :heart_eyes:

I also love the example villains (who, Boo excepted, were all mentioned as candidates to me!) but will people think maybe that they've already won? Should we say something like "What does it take to be a Ruby Villain?" or maybe they're "An Aspiring Villain's Villains"?

**Comment by davy** [comment]
Glad you like it!

So, I've been thinking a bit more about how this could be both a fun, tongue in cheek project, but also semi-serious as well. First, I think that just copying the Ruby Heroes model is kind of boring. Mainly because, well, that's what Ruby Heroes is for, and secondly, Ruby Villains don't follow rules. If Ruby Heroes have a central process, and are announced at RailsConf, then Ruby Villains should _not_ have a set process, and perhaps people could be awarded throughout the year? What if any Ruby Conference was allowed to award a Ruby Villain or two? To encourage hijinks and community building. And each conference could use whatever model it wanted to make awards - nominations and voting, surprise awards, 'best talk', blackmail, whatever.

I think that having people who are Ruby Villains have a villain name is a good idea, mainly because it helps cement the idea that the goal isn't to make anyone feel bad, and helps make it more fun. Plus then we could create sets of special villain stickers. Yeah, stickers!

I wanted to add some Villains to the page to start with because I think having some examples will help people get the idea better. Also it was just a bit picture-less. The few that I've added are people who probably don't want/need an "awards ceremony" since they are already pretty well known. If there are already a few Villains, we can build out the 'brand' a bit more, and I think that would get people excited and could encourage some Ruby Conferences to think about awarding some Villains of their own.

Thoughts? Other ideas?

**Comment by kerrizor** [comment]
Omg yes this is a GREAT idea. I see what you were going for and I love it! I /do/ still like the idea of a raucous event for giving out awards but maybe there like a league of ruby villains thing.. But definitely yes to what you said here, especially the idea of working with conferences to have each do a few villain awards (pipe dream of a special shirt or trophy or token of villainy...) as local community building..

Merging!

**Comment by davy** [comment]
VILLAINCONF

**Pull request merged**
